export const CHANGE_BUTTON='CHANGE_BUTTON'
export const CHANGE_CLICK='CHANGE_CLICK'

export const GET_QUESTIONS='GET_QUESTIONS'
export const GENERIC_USER_DATA_CHANGE='GENERIC_USER_DATA_CHANGE'
export const GET_QUESTIONS_COPY='GET_QUESTIONS_COPY'
export const GET_HISTORIES='GET_HISTORIES'
export const MANIPULATE_END_EXAM_BUTTON='MANIPULATE_END_EXAM_BUTTON'
export const CHANGE_PAGE='CHANGE_PAGE'

export const GENERIC_CHANGE='GENERIC_CHANGE'
export const INIT='INIT'






